rule personalize:
    input:
        data="../dataset/Fumia_META_mutCNA.csv",
        config="../config/conf.yaml"
    output:
        directory("output")
    shell:
        "permedcoe execute building_block sample_BB -i {input.data} -o {output} -c {input.config}"
